wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1693962340.109552
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      - 105
      3:
      - 13
      - 23
      4: 3.10.11
      5: 0.15.8
      8:
      - 2
      - 5
